# This is a configuration file for various technical indicators used in trading strategies.
# Each indicator has its own parameters that can be adjusted based on the trading strategy.
indicators:
  1h: # Hourly indicators
    adx: # Average Directional Index
      length: 14 
    atr: # Average True Range
      length: 14
    bbands: # Bollinger Bands
      length: 20
      stddev: 2.0
    macd: # Moving Average Convergence Divergence
      fast: 12
      slow: 26
      signal: 9
    rsi: # Relative Strength Index
      length: 14

  1d: # Daily indicators
    adx: # Average Directional Index
      length: 14 
    atr: # Average True Range
      length: 14
    bbands: # Bollinger Bands
      length: 20
      stddev: 2.0
    macd: # Moving Average Convergence Divergence
      fast: 12
      slow: 26
      signal: 9
    rsi: # Relative Strength Index
      length: 14
  

